# Problem Set 2

### 1.1

In [2]:
# Creating a list
p1_list = [4, 26, 93]

In [7]:
# Printing Min, Max, and Avg.
print(min(p1_list), max(p1_list), sum(p1_list) / 3)

4 93 41.0


### 1.2

In [16]:
# Integer - Immutable
int_1 = 42
int_2 = int_1
int_2 = 83
int_2 == int_1

False

In [17]:
# String - Immutable
str_1 = 'Campbell'
str_2 = str_1
str_2 = 'Not Me'
str_2 == str_1

False

In [18]:
# List - Mutable
list_1 = ['Me', 'You', 'Her', 'Him']
list_2 = list_1
list_2[1] = 'Them'
list_1 == list_2

True

In [22]:
# Tuple - Immutable
tuple_1 = ('Win', 'Lose', 'Draw')
tuple_2 = tuple_1
tuple_2 += (1,)
tuple_1 == tuple_2

False

In [30]:
# Set - Mutable
set_1 = {'Win', 'Lose', 'Draw'}
set_2 = set_1
set_2.add('Forfeit')
set_1 == set_2

True

In [43]:
print(
    '''It is clear that if the experiment for the object is true, it is mutable. From that observation,
    we can see that lists and sets are mutable objects.

    The immutable objects show false, and are integers, strings, and tuples.''')

It is clear that if the experiment for the object is true, it is mutable. From that observation,
    we can see that lists and sets are mutable objects.

    The immutable objects show false, and are integers, strings, and tuples.


### 1.3

In [31]:
run calculator.py

Sum of 2 and 6: 8
Square Root of 4: 2
7


In [33]:
sum_arg(2, 8)

10

In [34]:
product_arg(10, 2)

20

In [35]:
hypotenuse(6, 8)

10.0

### 2.1

In [172]:
# Creating Arrays A and B and dot product A.B
import numpy as np

A = np.array([ [3, -1, 4], [1, 5, -9] ] )
B = np.array([ [2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3] ])

np.dot(A, B)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

### 2.2

In [173]:
A = np.array([ [3, 1, 4], [1, 5, 9], [-5, 3, 1] ])

np.array((-1 * A ** 3) + (9 * A ** 2) - (15 * A) )

array([[   9,   -7,   20],
       [  -7,   25, -135],
       [ 425,    9,   -7]])

### 2.5

In [178]:
A = np.array( [ [0, 2, 4], [1, 3, 5] ] )
B = np.array( [ [3, 0, 0], [3, 3, 0], [3, 3, 3] ] )
C = np.array( [ [-2, 0, 0], [0, -2, 0], [0, 0, -2] ] )
Z = np.zeros( (3,3) )
Z_2 = np.zeros( (2,2) )
Z_3 = np.zeros( (3,2) )
Z_4 = np.zeros( (2,3) )
I = np.identity(3)
AT = A.transpose()

top = np.vstack( (Z, A, B) )
middle = np.vstack( (AT, Z_2, Z_3) )
bottom = np.vstack( (I, Z_4, C) )
np.column_stack( (top, middle, bottom) )

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

### 3.1

In [126]:
class Backpack:
    '''
    This is a backpack class. Enter the owner name, the color of the bag, and the maximum number of items it can hold.
    Then, you can use put() to add items, take() to remove them, and dump() to empty the backpack
    '''
    def __init__(self, name, color, max_size = 5):
        self.name = name
        self.color = color
        self.contents = []
        self.max_size = max_size
    def put(self, item):
        if len(self.contents) > 4: # Not sure how to get the No more room statement
            print("No more Room!")
        else:
            self.contents.append(item)
    def take(self, item):
        self.contents.remove(item)
    def dump(self):
        self.contents.clear()

In [127]:
my_pack = Backpack("Campbell", "Red")

In [128]:
my_pack.put("Pencil")
my_pack.put("Eraser")
my_pack.put("Paper")
my_pack.put("Book")

In [129]:
my_pack.contents

['Pencil', 'Eraser', 'Paper', 'Book']

In [130]:
my_pack.put("Calculator")

In [131]:
my_pack.put("Binder")

No more Room!


In [132]:
my_pack.contents

['Pencil', 'Eraser', 'Paper', 'Book', 'Calculator']

In [133]:
my_pack.dump()

In [134]:
print(my_pack.name, my_pack.color)

Campbell Red


In [135]:
my_pack.put("Pencil")
my_pack.put("Eraser")
my_pack.put("Paper")
my_pack.put("Book")
my_pack.put("Calculator")

In [136]:
print(my_pack.name, my_pack.color, my_pack.contents)

Campbell Red ['Pencil', 'Eraser', 'Paper', 'Book', 'Calculator']


### 3.2

In [159]:
class Jetpack(Backpack):
    def __init__(self, name, color, max_size = 2, fuel = 10):
        self.fuel = fuel
        self.contents = []
        self.name = name
        self.color = color
        self.max_size = max_size
    def fly(self, fuel):
        if self.fuel < fuel:
            print("Not enough fuel!")
        else:
            self.fuel = self.fuel - fuel
    def dump(self):
        self.contents.clear()
        self.fuel = self.fuel - self.fuel
    def put(self, item):
        if len(self.contents) > 1:
            print("No more Room!")
        else:
            self.contents.append(item)

In [160]:
my_jetpack = Jetpack('Campbell', 'Orange')

In [161]:
my_jetpack.fly(4)

In [162]:
my_jetpack.fuel

6

In [163]:
my_jetpack.fly(9)

Not enough fuel!


In [164]:
my_jetpack.put("Oxygen Tank")

In [165]:
my_jetpack.contents

['Oxygen Tank']

In [166]:
my_jetpack.put("a")

In [167]:
my_jetpack.put("b")

No more Room!


In [168]:
my_jetpack.dump()

In [169]:
my_jetpack.fuel

0

In [170]:
my_jetpack.contents

[]